root: true
env:
  node: true
  es2021: true
parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:prettier/recommended"
plugins:
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
settings:
  import/parsers:
    "@typescript-eslint/parser": [".ts", ".tsx"]
  import/resolver:
    typescript:
      project: ["./tsconfig.json"]
  react:
    version: detect
rules:
  eol-last:
    - warn
  no-console:
    - warn
  indent:
    - warn
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - never
  newline-per-chained-call:
    - warn
    - ignoreChainWithDepth: 2
  sort-imports:
    - warn
    - allowSeparatedGroups: true
      ignoreDeclarationSort: true
  import/order:
    - warn
    - alphabetize:
        order: asc
      newlines-between: always
      groups:
        [
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
          "type",
        ]
      pathGroups:
        - pattern: "@src/*"
          group: parent
        - pattern: "./**"
          group: sibling
    prettier/prettier: 
      - warn
        singleQuote: false,
        semi: false,
        tabWidth: 2,
        trailingComma: "es5",
        printWidth: 99